x-target: &target-params
  build: ./target-node
  depends_on:
    - control-node
  command: /sbin/init
  privileged: true
  tty: true

services:
  control-node:
    build: ./control-node
    container_name: control-node
    hostname: control-node
    init: true
    tty: true

  target-node1:
    <<: *target-params
    container_name: target-node1
    hostname: target-node1

  target-node2:
    <<: *target-params
    container_name: target-node2
    hostname: target-node2
